### PR TITLE
Support "legend: true"

### LINKED ISSUE #50: Provide a legend option
It would be beneficial to have a legend option available.  If the material is exported into SVG or PDF with no legend, clarity is lost to the audience if they do not know what the node colour codes mean.

### PR DESCRIPTION
**Pull request by rpetrich**
Closes #50

### CODE REVIEW

**Comment by huornlmj** [comment]
Yay!  When will this be available at https://www.deciduous.app @rpetrich ?

**Comment by rpetrich** [comment]
It is live now. Deciduous uses continuous deployment, so whenever a pull request merges it's changes are deployed.

**Comment by huornlmj** [comment]
I've tried it on some of my attack trees and I'm getting odd messages like:

Error: @S

when adding the `legend: true` to it.

image

**Comment by rpetrich** [comment]
@huornlmj could you post the contents of the text editor pane or, if it's private, a redacted version that still has the issue?

**Comment by huornlmj** [comment]
Try this, I tried it in Chrome, Vivaldi and Firefox, in private mode and normal mode. also tried clearing cache.

First, paste the below example.  It should look like this:

image

Once pasted, put a new line under the title: entry.  As you start to type `legend: true`, you will see the odd characters once you complete the word `true`.

```yaml
title: Test attack tree

facts:
- t_a: Type A
  from:
  - reality
- t_b: Type B
  from:
  - reality
- t_c: Type C
  from:
  - reality
- t_d: Type D
  from:
  - reality
- t_e: Type E
  from:
  - reality

attacks:
- attack_1: Attack number 1
  from:
  - t_a
- attack_2: Attack number 2
  from:
  - t_a
- attack_3: Attack number 3
  from:
  - t_a
- attack_4: Attack number 4
  from:
  - t_b
- attack_5: Attack number 5
  from:
  - t_c
- attack_6: Attack number 6
  from:
  - t_d
- attack_7: Attack number 7
  from:
  - t_d
- attack_8: Attack number 8
  from:
  - t_d
- attack_9: Attack number 9
  from:
  - t_e

mitigations:
- mitigation: Mitigation?
  from:
  - attack_1
  - attack_2
  - attack_3
  - attack_4
  - attack_5
  - attack_6
  - attack_7
  - attack_8
  - attack_9

goals:
- goal_1: Goal number 1
  from:
  - attack_1
  - attack_2
  - attack_3
- goal_2: Goal number 2
  from:
  - attack_4
- goal_3: Goal number 3
  from:
  - attack_5
- goal_4: Goal number 4
  from:
  - attack_6
  - attack_7
  - attack_8
- goal_5: Goal number 5
  from:
  - attack_9
```

**Pull request merged**
